### ISSUE TITLE
Indicator Circle not Present

### ISSUE THREAD

**Issue by psurace** [Flafla2/Vive-Teleporter#15] opened 2016-06-05 22:22 UTC
Hey There,

I have this set up as correctly as I can imagine.  I'm sure it's still user error.  I get the Parabolic line work, but no "target" circle or orange border on the floor.  Also upon pressing, it doesn't teleport, should it?.

**Comment by Flafla2** [comment] 2016-06-05 23:02
Make sure you have correctly configured your Vive Nav Mesh.

[See here for more information regarding this](https://github.com/Flafla2/Vive-Teleporter#step-1-configure-the-vive-nav-mesh).

**Comment by psurace** [comment] 2016-06-06 05:35
What could I do to double check.  Everything seems in order with your process?

**Comment by psurace** [comment] 2016-06-07 02:35
So here's what I'm seeing.

This is your example file.

![yours](https://cloud.githubusercontent.com/assets/18473105/15844278/b8ccb052-2c1d-11e6-9cc1-f65f40de7f41.PNG)

And my file.  That green ball I assume is suspect?

![mine](https://cloud.githubusercontent.com/assets/18473105/15844283/c47621c2-2c1d-11e6-9bba-d020d9fc3d1f.PNG)

**Comment by psurace** [comment] 2016-06-07 02:36
I live in Los Angeles, but I'm from Staten island BTW...ha.

**Comment by Flafla2** [comment] 2016-06-07 02:48
Have you set the "Nav Mesh" property of the Parabolic Pointer? (topmost property)

![](https://camo.githubusercontent.com/5e30b3e2517f515680fc3b16dcd020903dd69c96/687474703a2f2f692e696d6775722e636f6d2f30306f42724f6d2e706e67)

**Comment by psurace** [comment] 2016-06-07 03:24
These are the added parts to Unity In my file.

On the Camera:
![onrig](https://cloud.githubusercontent.com/assets/18473105/15845104/a8162c64-2c24-11e6-8d08-8142506c93ea.PNG)

NavMesh/:
![navmesh](https://cloud.githubusercontent.com/assets/18473105/15845110/b280f3be-2c24-11e6-89c3-375698130fc6.PNG)

Pointer:
![pointer](https://cloud.githubusercontent.com/assets/18473105/15845116/b8c76a00-2c24-11e6-89a2-37fb754edb9a.PNG)

**Comment by psurace** [comment] 2016-06-07 03:26
Really appreciate everything BTW...for sure.

**Comment by Flafla2** [comment] 2016-06-07 03:43
Do you have colliders on all of the selectable objects?

If not you need them.  Otherwise could you send me an example scene?
- Adrian

**Comment by psurace** [comment] 2016-06-07 15:19
Here it is.  If you could also (I know I'm a pest but I'm East Coast at least!!!), break down what I did wrong?  Then I wont bother you about it ever again once I learn :-).

Files Here.
www.patricksurace.com/transfer/VIVEAlive.zip

Thanks so much!

-Patrick

**Comment by Flafla2** [comment] 2016-06-07 15:43
It appears you have no [Teleport Vive](https://github.com/Flafla2/Vive-Teleporter#step-3-configure-the-vive-teleporter) component attached to the camera.  Add that to the Camera (eye) object in your scene and assign the properties as discussed in the linked how-to and you should be good.

**Note: The Teleport Vive component MUST be attached to the rendering camera, NOT the [CameraRig] object!**

**Comment by psurace** [comment] 2016-06-07 17:59
Interesting.  I tried "fixing it", no dice.  I did it over and now I don't get the Parabolic Line anymore either and it still doesn't teleport?  Did you get it working there?  I appreciate your time man...Maya I know, Unreal I know better....Unity is like a week old for me, sorry.

**Comment by Flafla2** [comment] 2016-06-07 18:18
Teleport vive plugs into the camera's rendering callbacks, that's why it must be attached o a camera.  Does the example scene work?

**Comment by psurace** [comment] 2016-06-07 18:24
The example scenes work perfectly.  But I don't know Unity well enough to know if I messed anything up trying to "remove all components" and redo-ing it.  Is that a scenario?  Left over pieces can screw me?

**Comment by psurace** [comment] 2016-06-07 18:26
Why would things like the "Parabolic Selector" Material disconnect?  It appears to be there in the pointer graphic material section but didn't show up in the VIVE until I remap its connection?

**Comment by Flafla2** [comment] 2016-06-07 18:26
No, if you get rid of everything and try again there shouldn't be a problem.  Try starting over and follow the tutorial instructions very carefully.

**Comment by psurace** [comment] 2016-06-07 18:27
Also, I know this is "user error" but you made this thing and it works so well in your example...I want to use it...I'll gladly do anything 3D I can for you, just ask :-)  That's why I keep bugging you, haha!

**Comment by Flafla2** [comment] 2016-06-07 18:46
In the next update I might remove the need to use TeleportVive and configure it automatically.  It seems like it is the biggest cause of user error

**Comment by psurace** [comment] 2016-06-07 18:51
Well I'm sure after 4 months with Unity, I'd be like "of course that didn't work".  But as of now, no...I have no idea.  Your tutorial works very well too, it was easy to understand.  My controllers died, HA  I'll check my newest again soon.  I got my Visual parabolic Selector in the Unity Viewport again, so that's a plus.  However I have never seen the "Green" sphere that is pictured above in MY scene...what is that and what should it be attached to?  I want to say it's the indicator circle, which I also never see in my "Play" on the VIVE.  All yours work fine, obviously that's what I'm testing, back and forth.

**Comment by psurace** [comment] 2016-06-07 22:56
I'm getting closer. I have one cube in here that is "grab-able" that is the only thing that will reveal the "destination circle" and teleporting there works...nothing else does though.

**Comment by psurace** [comment] 2016-06-07 23:15
Is it too much to ask for you to look at my file and see if there's anything that might be going on in my code for the grab able objects is conflicting with your stuff?

**Comment by local306** [comment] 2016-06-10 02:39
Hey, so I was having the same issue as the OP. I followed the instructions step-by-step verbatim and could not get the asset to work as it does in the demo scene.

Finally, for whatever reason, I decided to add in an additional object and assign it a user defined navigational area like the AI Only tag in the demo scene. Miraculously, this solved the problem. I've been trying to scour through the code to see what's up but I haven't had too much of a chance to dig deeply.

Is there any reason why this wouldn't work when a use defined nav area isn't defined?

**Comment by Flafla2** [comment] 2016-06-10 12:20
@local306 Sounds like a bug obviously.  I'll look into it ASAP.

**Comment by psurace** [comment] 2016-06-10 15:54
@Flafla2, you've stopped answering me.  I was tired of trying your file  but found this @local306.  "Steam_VR_Unity_Toolkit".  Has two kinds of pointers and a lot more examples...and they work.  I really don't understand how come you never tried opening my file to try this after I asked (with compliments) 14 times :-).

**Comment by local306** [comment] 2016-06-10 16:20
@psurace I have tried out the toolkit you mentioned, but I wasn't overly impressed by the teleportation's aesthetics. The arc is sloppy and doesn't handle as well as this package.

**Comment by psurace** [comment] 2016-06-10 16:53
@local306 totally agree...if you dig in it's alterable alot.  as you can see above the interest in helping me stopped so I'm making it work".

**Comment by Flafla2** [comment] 2016-06-10 18:02
@psurace

Let's be perfectly clear: I am providing this API as a free contribution to the Vive development community.  I had considered selling it on the asset store-in my opinion it is superior to the $5 asset that is currently up there.  But instead I open sourced it to give back.

I have never committed to 24/7 support, because I was never paid to.  Of couse I have tried to field questions when I can, but to expect me to do so within days is ridiculous and insulting.  I haven't "lost interest" in your issue-I was at my high school senior prom and simply didn't have the time.  If you are interested in paying me for dedicated support please contact me.

From all the testing that I have done, the provided Get Started guide is sufficient to get a demo running.  @local306 has suggested that there may be a bug preventing this, and I will take a look when I can.  I apologize for the inconvenience and will update you when I have investigated the issue further.  I will also look into reducing the complexity of setup.

If you find the root of this issue feel free to fix it and submit a pull request.  Otherwise I'll get around to it at a time best for me.

**Comment by FuzzyWuzzie** [comment] 2016-06-10 18:15
@psurace you are incredibly rude, and quite frankly I think your attitude here demonstrates that you are entirely undeserving of help. Github is not a place for you to just grab free things and get support for free. 

@Flafla2 has created an open source project, 100% volunteering his time and effort, and is making a great package that others are using and/or referencing without issue (myself included). The audacity of you to come in here, demanding _immediate_ help, from a stranger, who is already volunteering their time, on a project for all we know you will make money off of, is incredibly insulting. I suggest you take a look at the [license](https://github.com/Flafla2/Vive-Teleporter/blob/master/LICENCE.txt), and specifically note the parts about warranties.

If you'd rather go use another library, then by all means do so; nothing is keeping you here. But don't act like a spoiled child in someone else's house. I can guarantee you that you will never do anything of value in life if you carry on that way.

**Comment by psurace** [comment] 2016-06-10 20:09
Guys, @FuzzyWuzzie and @Flafla2 if you can't real (since I'm incredibly rude)..."Also, I know this is "user error" but you made this thing and it works so well in your example...I want to use it...I'll gladly do anything 3D I can for you, just ask :-) "  that seems like some sort of "payback" for help.  Maybe you both need a lesson in American English?  Before you get involved @FuzzyWuzzie ...the guy asked for my file.  If he actually opened it after asking, maybe I wouldn't have to say "as you can see above the interest in helping me stopped so I'm making it work".  Understandably so that your files are free @Flafla2 ...  but with the way you treat it, it's WORTH $5 for files that work.  Get over yourselves.

**Comment by psurace** [comment] 2016-06-10 20:11
Also, imagine the feedback if people PAID for these buggy assets?  you did yourself a favor not charging.

**Comment by psurace** [comment] 2016-06-10 20:27
The one thing I can and will apologize for is hoping for a return fix faster than 3 days.  I work all the time and am always at a computer, how could I know that's not the case for others involved in this field, it usually is.  Clients send me things, they say "check this out" and I can...immediately.  You asked me for a file, I assumed because you were interested to fix that file.  For me that would mean, "when the file is delivered to me".  I apologize for hoping your turnaround would be faster.  I could also not know that you're going to High School prom.

**Comment by local306** [comment] 2016-06-13 17:45
I think it may have been a stroke of luck, but I was unsuccessful at recreating the success I had from the first time around. I followed the instructions as laid out in the help section but it never configures properly. 

I do have my previous scene working which I duplicate and start from there.

**Comment by psurace** [comment] 2016-06-13 18:46
Unfortunately I've tried it over and over.  Still doesn't work for me.  I am not a coder though, so I guess I'm out of luck.

**Comment by DaveLMyers** [comment] 2016-06-14 21:20
If I change the Agent Radius on the Navigation tab from the default of 0.50 to 0.1 and the Step Height from the default of 0.4 to 0.15, the green sphere on the Pointer shows up and I can teleport.

**Comment by Xen0phobe** [comment] 2016-06-20 22:46
@psurace I was having the same problem. Following @DaveLMyers advice got it working.

**Comment by Flafla2** [comment] 2016-06-21 12:32
@DaveLMyers Thanks for the investigation.  It appears that more processing / filtering needs to be done to the Unity Navmesh to import properly.  I believe it has to do with the "Step Height" parameter (in my testing Agent Radius hasn't had any impact).

Can you provide an example scene where you are having problems?

**Comment by mikeshultz** [comment] 2016-06-26 17:18
Confirmed.  Agent Radius was the killer for me.  My step height remains at 0, which is all I need.  Having to have such a small agent radius kind of sucks for me, though, because I would like it much larger for my AI.  Pretty new to unity but I'll continue looking into this and will let you know if I figured anything else out.

@DaveLMyers Thanks for the info.

**Comment by mikeshultz** [comment] 2016-06-26 18:13
After further messing with it, you can set a higher agent radius as long as you set a manual voxel size.  For my test I used an `Agent Radius` of 5, `Voxel Size` of 0.05, and a `Min Region Area` of 3.  It takes quite some time to bake, but if you need to go that route, it is doable.

**Comment by Flafla2** [comment] 2016-12-27 05:03
Hello everyone, I recently bought a Vive so I can now work on this API again (after moving workplaces I lost access to one).  I believe I have identified the issue here, and it has to do with a mismatch between the ``Voxel Size`` discussed above and the sampling radius that I use in my scripts (see [this line](https://github.com/Flafla2/Vive-Teleporter/blob/48898177e9434ba012addb65bc218b48fc5664ca/Assets/Vive-Teleporter/Scripts/ViveNavMesh.cs#L205)).  I use the sampling radius 0.05 there, which is greater than the Navigation voxel size in the sample scene (0.033).  However, if the voxel sizes in your scenes are greater than 0.05 (which is very possible especially for larger scenes) then the issues discussed here would begin to pop up.

The solution presented in #31 agrees with this theory.  So I'm going to add a "Sample Radius" parameter to TeleportVive, that you can increase if you have issues.

Luckily with Unity 5.6 I can actually automate this - Unity has greatly improved their Navmesh API in the beta.  Jakob from Unity actually [replied recently to my Unity issue](https://feedback.unity3d.com/suggestions/expose-navigation-settings-to-editor-scripts) regarding this, so it's great to see that these issues have been addressed.  For 5.5 and below however, these parameters will need to be manually given.

**Comment by Flafla2** [comment] 2016-12-27 05:54
See 8edbc61 for an implementation of the above fix

**Closed as completed** 2016-12-27 05:53 UTC
Labels: bug
